### PR TITLE
Added ThreadPoolExecutors

### PR DESCRIPTION
**Pull request by LunaCodeDemon**
I added some thread pools around the slow loops.
I wouldn't allow myself to make mistakes with `multiprocessing`, found out that threads in those cases have some performance advantages.

The second threat pool is commented out since I wasn't able to test it.

### CODE REVIEW

**Comment by ChinoCodeDemon** [comment]
Need help to implement a test for `biaxial_bending_diagram`, since I don't know really what it produces.

**Comment by robbievanleeuwen** [comment]
Hi @ChinoCodeDemon,

Based on my limited knowledge, I would have thought that threading wouldn't really make a difference since the computation isn't limited by I/O operations, rather it is limited by python executing on only one CPU core. My understanding is that in this case ``multiprocessing`` should be used rather than ``threading`` as we have a loop which executes independent calculations.

Let me know your thoughts.

**Comment by ChinoCodeDemon** [comment]
Well the already existing test, was even slower with multi processing, probably because the processes needed some time to boot up.
It could tho be a problem with Ryzen processors.
If you want to test it yourself, you can easily replace Thread pool executor with Process pool executor.

**Comment by robbievanleeuwen** [comment]
Yes the boot up time could be an issue. Perhaps this is more suited for an application to the biaxial bending problem only rather than the interaction diagram problem.

On my computer the biaxial calculation takes 5-6 seconds for a typical cross-section, whereas the interaction diagram only takes approx 0.3 seconds. I'm wondering if it's best just to focus on the biaxial bending calculation?

**Comment by ChinoCodeDemon** [comment]
I think depending on the size of operations we would have to also make a decision at what point a procedural calculation would work at similar speed.
Probably lists with less than 16 values might be slower with multi processing.

**Comment by robbievanleeuwen** [comment]
Let's stick to just the biaxial calculation at the moment. This is more involved computation as there is an iterative solver ``scipy.optimize.brentq`` that must converge for each value of ``theta``.

I see you have a static value for how you split up the list (chunks). Is there not a way for python to do this dynamically? E.g. when I initially had a look at this it seemed like ``multiprocessing`` had a way to do this with process pools, see [here](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.pool).

**Comment by ChinoCodeDemon** [comment]
I have now less time for hobbyistic development, either the progress on this will be slower or we just use the stuff where we are already sure that it works.
I think it's just fair that I inform you about it, might not be the best experience to wait long for a more or less simple patch.

**Comment by ChinoCodeDemon** [comment]
> Let's stick to just the biaxial calculation at the moment. This is more involved computation as there is an iterative solver ``scipy.optimize.brentq`` that must converge for each value of ``theta``.
> 
> I see you have a static value for how you split up the list (chunks). Is there not a way for python to do this dynamically? E.g. when I initially had a look at this it seemed like ``multiprocessing`` had a way to do this with process pools, see [here](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.pool).
> 
I currently don't know how to use Process pool, I will try to inform myself about it as good as I can. Currently I don't know if it's the correct solution for the problem.

For now I will stick to list splitting, since it's a reliable way to separate the data into chunks.

For the number I choose 16 since most processor counts are increasing in base 2  and 16 is the assumed maximum beneficial core count, the map function will handle the execution of those 16 chunks automatically and goes to the next chunk once a thread/process is available. Newer desktop CPUs of the Ryzen 9 series already have 32 cores so there would be the possibility to increase it to 32 if the core count is above 16.

I don't know tho how to calculate the chunks needed to get certain efficiency since the language can't know how fast the execution of one chunk will be it's hard to dynamically chunk the data, best bet would be setting it to core count but even that might be also a bad approach for smaller datasets.

**Comment by ChinoCodeDemon** [comment]
From first overview it seems that the newer Process pool executor and Thread pool executor are somewhat based on the multiprocess pool.

**Comment by ChinoCodeDemon** [comment]
I noticed that I don't need to check for the CPU count in the creation of the process executor and it will automatically manage the pool.

**Review by ChinoCodeDemon — COMMENTED** [review]
Numba would be a good addition to this.
Depending on the boost it gives it could improve the performance by a huge amountm, by pre-compiling calculations into machine code.
https://numba.pydata.org/

**Comment by ChinoCodeDemon** [comment]
I now made the chunks have a constant size of 128, meaning that the thread/process has to start working on the next chunk when it's done.
I would set this according to the complexity of the task.

**Comment by ChinoCodeDemon** [comment]
I will just mark this as ready for review if you want some edits i can look over it.

**Pull request closed without merging**
