### PR TITLE
Interaction diagram features

### LINKED ISSUE #20: Interaction Diagram Features
### Discussed in https://github.com/robbievanleeuwen/concrete-properties/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **Agent6-6-6** July 23, 2022</sup>
*"Many codes ACI318 and NZS3101 have a hard upper cutoff for the axial load a section can take... additionally it may be useful to also report the control points and have an option to plot these points on the interaction curves?"*

**Features to add to ``moment_interaction_diagram()``:**
- Option to provide upper compression limit to interaction curve, i.e. ``max_comp: Optional[float] = None``.
- Add optional control points and labels. Control points are given axial forces or neutral axis depths (useful for balanced/strain points) which get added to the interaction diagram. There will be an optional corresponding list of labels which relates to these control points. By default control points are defined at decompression (``d_n=D``) and pure bending (``N=0``).
- Extend ``n_points`` to also have the option of providing a list between control points. By default a single value is provided, say 24. If more control points are provided this can be extended to a list e.g. [10, 24] is 10 points between 1st and 2nd control point and 24 points between 2nd and 3rd control point.

### PR DESCRIPTION
**Pull request by robbievanleeuwen**
Adds features to the moment interaction diagram listed in that resolves #20.

### CODE REVIEW

**Comment by robbievanleeuwen** [comment]
@Agent6-6-6 & @connorferster this PR is ready for a review if you are interested in having a play before I merge. Interested in any feedback you both have!

Below are a few examples showing the features.

**Comment by robbievanleeuwen** [comment]
**Max Compression**

```python
mi_res = mi_res = conc_sec.moment_interaction_diagram()
mi_res_max_comp1 = conc_sec.moment_interaction_diagram(max_comp=6500e3)
mi_res_max_comp2 = conc_sec.moment_interaction_diagram(max_comp=6000e3)
MomentInteractionResults.plot_multiple_diagrams(
    [mi_res, mi_res_max_comp1, mi_res_max_comp2],
    labels=["Original", "Max Comp 1", "Max Comp 2"],
    fmt="-",
)
```
Screen Shot 2022-07-29 at 5 47 46 pm

**Comment by connorferster** [comment]
It looks great, @robbievanleeuwen!

I noticed you removed the m_neg parameter. Why was that?

I am going on a vacation for four days so I won't be able to play around with it but, like I said, it looks great!

**Comment by robbievanleeuwen** [comment]
Thanks @connorferster, enjoy your break! I removed it because it was superfluous (very easy to generate another moment interaction diagram with the angle rotated 180 degrees) and it complicated the implementation of these features unnecessarily. I updated the moment interaction example in the docs to show how the negative plot can still be done quite easily.

**Comment by connorferster** [comment]
That makes total sense! Good call!

**Comment by Agent6-6-6** [comment]
@robbievanleeuwen, yeah that looks good. 

A few thoughts:-

Regarding the m_neg thing, could there be an input variable to the generation of the interaction diagram that was true/false that just did the angle+180 degrees and appended results and returned the entire positive and negative diagram for plotting. Return positive diagram by default, otherwise do a further loop internally at angle + 180 degrees and return both neg and positive diagrams in a seemless manner to the user? 

Also by default should the normal control points include all the typical points of interest as per my diagram in #12, or at least have the option of doing that. Thinking/reasoning is that saves user doing it in their own code as 99% of the time you're going to just want those common points and not have to go through and build up the control points as per your example gist. Just break it out into another function that is called to populate the control points list? Could have a couple of typical predefined scenarios that could be called depending on your needs regarding plotting, like for example

> full (every typical point - max axial load at zero moment, max moment at max axial load, 50% strain, 0% strain, etc, etc), 

> intermediate (maybe just 50% strain, balance point, etc), 

> or min (maybe just the balance point)

If a specific code has other points of interest (like points where strength reduction factors change for example) then you include that in the relevant Design Code class when you call the interaction diagram and they are appended to the defined default control point list?

**Comment by Agent6-6-6** [comment]
>Regarding the m_neg thing, could there be an input variable to the generation of the interaction diagram that was true/false that just did the angle+180 degrees and appended results and returned the entire positive and negative diagram for plotting. Return positive diagram by default, otherwise do a further loop internally at angle + 180 degrees and return both neg and positive diagrams in a seemless manner to the user?

Actually I see that is what n_neg used to do...... fail. I still think this is quite useful in reducing the amount of user code to get  a result, but if caused to many issues then so be it!

**Comment by robbievanleeuwen** [comment]
Good idea, I will add another point type to ``control_points`` which will essentially be the yield ratio of the most extreme tensile bar. E.g. 0 will be zero strain, 0.5 will be 50% strain and 1 will be balanced strain.

I will change the default control points as well.

**Comment by robbievanleeuwen** [comment]
Having the balanced point included as default will also resolve #21 as this is where the transition occurs.

**Comment by Agent6-6-6** [comment]
> Having the balanced point included as default will also resolve #21 as this is where the transition occurs.

Yeah, some codes will have other points that don't correspond to just the balanced strain. So having a method for injecting those from the design code call would be needed (which I assume would be easily achieved with what's proposed with the ratio?) 

For example ACI318 factors

**Comment by robbievanleeuwen** [comment]
Not super familiar with the symbols used in ACI but yes this should be possible. You can now enter a factor that is essentially the strain in the steel divided by the yield strain which should be able to cover these cases.

**Pull request merged**
